import {
    faSun,
    faCloudSun,
    faCloud,
    faSmog,
    faCloudRain,
    faCloudShowersHeavy,
    faSnowflake,
    faBolt,
    faCloudBolt,
    faCloudRainHeavy,
    faCloudSunRain,
} from '@fortawesome/free-solid-svg-icons';

const weatherCodeMap = {
    0: { icon: faSun, label: 'Clear sky' },
    1: { icon: faCloudSun, label: 'Mainly clear' },
    2: { icon: faCloudSun, label: 'Partly cloudy' },
    3: { icon: faCloud, label: 'Overcast' },
    45: { icon: faSmog, label: 'Fog' },
    48: { icon: faSmog, label: 'Depositing rime fog' },
    51: { icon: faCloudRain, label: 'Light drizzle' },
    53: { icon: faCloudRain, label: 'Moderate drizzle' },
    55: { icon: faCloudShowersHeavy, label: 'Dense drizzle' },
    56: { icon: faCloudRain, label: 'Light freezing drizzle' },
    57: { icon: faCloudShowersHeavy, label: 'Dense freezing drizzle'},
    61: { icon: faCloudShowersHeavy, label: 'Slight rain' },
    63: { icon: faCloudShowersHeavy, label: 'Moderate rain' },
    65: { icon: faCloudShowersHeavy, label: 'Heavy rain' },
    66: { icon: faCloudRain, label: 'Light freezing rain' },
    67: { icon: faCloudShowersHeavy, label: 'Heavy freezing rain' },
    71: { icon: faSnowflake, label: 'Slight snow fall' },
    73: { icon: faSnowflake, label: 'Moderate snow fall' },
    75: { icon: faSnowflake, label: 'Heavy snow fall' },
    77: { icon: faSnowflake, label: 'Snow grains' },
    80: { icon: faCloudShowersHeavy, label: 'Slight rain showers' },
    81: { icon: faCloudShowersHeavy, label: 'Moderate rain showers' },
    82: { icon: faCloudShowersHeavy, label: 'Violent rain showers' },
    85: { icon: faSnowflake, label: 'Slight snow showers' },
    86: { icon: faSnowflake, label: 'Heavy snow showers' },
    95: { icon: faBolt, label: 'Thunderstorm' },
    96: { icon: faCloudBolt, label: 'Thunderstorm with slight hail' },
    99: { icon: faCloudBolt, label: 'Thunderstorm with heavy hail' },
};

export default weatherCodeMap;
